/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kr_tibyte_ndktest3_MainActivity */

#ifndef _Included_kr_tibyte_ndktest3_MainActivity
#define _Included_kr_tibyte_ndktest3_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kr_tibyte_ndktest3_MainActivity
 * Method:    getNativeText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kr_tibyte_ndktest3_MainActivity_getNativeText
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
